automation:
  - id: b8433072-f1dd-411d-a261-17ed8860792c
    alias: NHT TV
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionID: D03A00DB-D822-4A8D-94E6-CA7A072DE4EF
          actionName: NHT TV
          sourceDeviceID: kashyyyk
          sourceDeviceName: Kashyyyk
          sourceDevicePermanentID: 36125E58-99DF-40EA-B840-76BD83C4133D
          triggerSource: watch
    condition: []
    action:
      - alias: "Run tv time"
        service: script.turn_on
        target:
          entity_id: script.nht_tv_time

  - id: 6d45d608-963b-4fa7-a9e9-f282c928465c
    alias: Arm/Disarm NHT
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionID: AFFFBF35-4801-4773-A8AC-D05B8DEE940B
          actionName: Disarm NHT
          sourceDeviceID: kashyyyk
          sourceDeviceName: Kashyyyk
          sourceDevicePermanentID: 36125E58-99DF-40EA-B840-76BD83C4133D
          triggerSource: watch
    condition: []
    action:
      - alias: "Conditionally arm/disarm"
        choose:
        - conditions:
            - alias: "NHT is disarmed"
              condition: state
              entity_id: alarm_control_panel.nht_home_alarm
              state: "disarmed"
          sequence:
            - alias: "Arm NHT for night"
              service: alarm_control_panel.alarm_arm_night
              target:
                entity_id: alarm_control_panel.nht_home_alarm
        default:
            - alias: "Disarm NHT"
              service: alarm_control_panel.alarm_disarm
              target:
                entity_id: alarm_control_panel.nht_home_alarm