sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    name: yourporter
    port: 993
    username: !secret google_imap_username
    password: !secret google_imap_password
    # folder: YOUR_FOLDER
    senders:
      - hello@yourporter.com
      - pfammatter@gmail.com
  - platform: template
    sensors: 
      yourporter_listing:
        friendly_name: Your Porter Listing
        value_template: >-
          {{ state_attr("sensor.yourporter", "body") |
             regex_findall_index("\$listing: (.*)\n")}}
      yourporter_in_date:
        friendly_name: Your Porter Checkin
        value_template: >-
          {{ state_attr("sensor.yourporter", "body") |
             regex_findall_index("\$inDate: (.*)\n")}}
      yourporter_out_date:
        friendly_name: Your Porter Checkin
        value_template: >-
          {{ state_attr("sensor.yourporter", "body") |
             regex_findall_index("\$outDate: (.*)\n")}}
      yourporter_guest_code:
        friendly_name: Your Porter Guest Code
        value_template: >-
          {{ state_attr("sensor.yourporter", "body") |
             regex_findall_index("\$guestCode: (\d{4})")}}