sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    name: yourporter
    port: 993
    username: !secret google_imap_username
    password: !secret google_imap_password
    # folder: YOUR_FOLDER
    senders:
      - hello@yourporter.com
      - pfammatter@gmail.com