notify:
  - name: michael
    platform: group
    services:
      - service: mobile_app_ergisch
  - name: angela
    platform: group
    services:
      - service: mobile_app_iphone
  - name: camille
    platform: group
    services:
      - service: mobile_app_moto_g_7_play
  - name: grown_ups
    platform: group
    services:
      - service: mobile_app_ergisch
      - service: mobile_app_iphone
  - name: nht_camille_tty
    platform: rest
    resource: http://192.168.40.159:8123/api/services/script/notify_camille_with_sound
    method: POST_JSON
    headers:
      Authorization: !secret nht_bearer
    message_param_name: message
  - name: pancab_camille_tty
    platform: rest
    resource: http://192.168.100.101:8123/api/services/script/notify_camille_with_sound
    method: POST_JSON
    headers:
      Authorization: !secret pancab_bearer
    message_param_name: message

automation:
  - id: '1607566508232'
    alias: Notify when remote connection is down
    trigger:
      - platform: state
        entity_id: 
          - sensor.remote_connection_to_192_168_100_101_8123
          - sensor.remote_connection_to_192_168_40_159_8123
        for: 00:00:30
    action:
      - service: notify.michael
        data:
          title: 'Master HA Alert'
          message: >-
            {%- if trigger.entity_id == 'sensor.remote_connection_to_192_168_100_101_8123' -%}
            {%- set connectionName = 'Pandemicabin' -%}
            {%- else -%}
            {%- set connectionName = 'North Harbor Tower' -%}
            {%- endif -%}
            {{connectionName}} is {{ trigger.to_state.state }}.