input_select:
  closest_home_michael:
    name: 'Closest Home Michael'
    options:
      - 'North Harbor Tower'
      - 'Pandemicabin'

automation:
  - id: '1608339069146'
    alias: 'Set closest home'
    variables:
      current_zone: >-
        {% if states('input_select.closest_home_michael') == 'Pandemicabin' -%}
        zone.cabin
        {%- else -%}
        zone.home
        {%- endif %}
      closest_zone: >-
        {{ closest(person.michael, states.zone).entity_id }}
    trigger:
      - platform: state
        entity_id: 
          - person.michael
    condition:
      - condition: template
        value_template: >-
          {{ closest_zone =! current_zone }}
    action:
      - service: input_select.set_options
        data:
          entity_id: input_select.closest_home_michael
          option: >-
            {% if closest_zone == 'zone.cabin' %}
            Pandemicabin
            {% else %}
            North Harbor Tower
            {%- endif %}
  # - id: '1608344953300'
  #   alias: 'Notify when away from Pandemicabin'
  #   trigger:
  #     - platform: state
  #       entity_id: entity id
  #       from:  from state
  #       to:  to state
  #   condition:
  #   action:

  - id: '1606702211014'
    alias: 'Pandemicabin notify when away'
    trigger:
      - platform: template
        value_template: >-
          {{ distance('zone.cabin', 'device_tracker.ergisch') >= 60 and
             distance('zone.cabin', 'device_tracker.iphone') >= 60 }}
        for: "00:45:00"
    condition:
      - condition: state
        entity_id:
          - input_boolean.pancab_heat_away
        state: 'off'
    action:
      - service: notify.grown_ups
        data:
          title: "Panemicabin Alert"
          message: "It appears you have left. Set the heat to away"
  - id: '1606704077554'
    alias: 'Pandemicabin notify when getting close'
    trigger:
      - platform: template
        value_template: >-
          {{ distance('zone.cabin', 'device_tracker.ergisch') <= 80 or
             distance('zone.cabin', 'device_tracker.iphone') <= 80 }}
        for: "00:15:00"
    condition:
      - condition: state
        entity_id:
          - input_boolean.pancab_heat_away
        state: 'on'
      - condition: numeric_state
        entity_id: 
          - sensor.pancab_temperature_overall
        below: 67
    action:
      - service: notify.grown_ups
        data:
          title: "Panemicabin Alert"
          message: "It appears you are heading to the cabin. You might want to make it warmer."
