google:
  client_id: !secret googleCalendarClientId
  client_secret: !secret googleCalendarSecret

automation:
  - id: 3140d905-bb2d-4328-b137-86cf628f8839b
    alias: Camille Notify on Calendar Event
    trigger:
      - platform: state
        entity_id: calendar.camille
        from: "off"
        to: "on"
    condition:
      - condition: not
        conditions:
          - alias: "Camille is home"
            condition: state
            entity_id: person.camille
            state: "away"
    action:
      - alias: "Pick a speaker to broadcast to"
        choose:
        - conditions:
            - alias: "Camille at nht"
              condition: state
              entity_id: person.camille
              state: "home"
          sequence:
            - service: notify.nht_camille_tty
              data:
                message: >
                  Camille, get ready for {{ state_attr('calendar.camille', 'message') }}
        - conditions:
            - alias: "Camille at cabin"
              condition: state
              entity_id: person.camille
              state: "Cabin"
          sequence:
            - service: notify.pancab_camille_tty
              data:
                message: >
                  Camille, get ready for {{ state_attr('calendar.camille', 'message') }}
      - service: notify.camille
        data:
          title: Calendar Alert
          message: >
            Camille, get ready for the {{ state_attr('calendar.camille', 'message') }}
      - service: notify.grown_ups
        data:
          title: Calendar Alert
          message: >
            Camille's Event: {{ state_attr('calendar.camille', 'message') }}
