input_select:
  closest_home_michael:
    name: 'Closest Home Michael'
    options:
      - 'North Harbor Tower'
      - 'Pandemicabin'
  closest_home_angela:
    name: 'Closest Home Angela'
    options:
      - 'North Harbor Tower'
      - 'Pandemicabin'
  closest_home_camille:
    name: 'Closest Home Camille'
    options:
      - 'North Harbor Tower'
      - 'Pandemicabin'

automation:
  - id: '1608339069146'
    alias: 'Set closest home michael'
    trigger:
      - platform: state
        entity_id: 
          - person.michael
        for: '00:05:00'
    condition: []
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.closest_home_michael
          option: >-
            {%- if closest('person.michael', states.zone).entity_id == 'zone.cabin' %}
            Pandemicabin
            {%- else -%}
            North Harbor Tower
            {%- endif -%}

  - id: a0a3998d-5577-4d88-b931-ae20ea18573e
    alias: 'Set closest home angela'
    trigger:
      - platform: state
        entity_id: 
          - person.angela
        for: '00:05:00'
    condition: []
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.closest_home_angela
          option: >-
            {%- if closest('person.angela', states.zone).entity_id == 'zone.cabin' %}
            Pandemicabin
            {%- else -%}
            North Harbor Tower
            {%- endif -%}
            
  - id: 98369a67-4c00-4402-a8d4-abc62043f30b 
    alias: 'Set closest home camille'
    trigger:
      - platform: state
        entity_id: 
          - person.camille
        for: '00:05:00'
    condition: []
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.closest_home_camille
          option: >-
            {%- if closest('person.camille', states.zone).entity_id == 'zone.cabin' %}
            Pandemicabin
            {%- else -%}
            North Harbor Tower
            {%- endif -%}
            
  - id: '1608344953300'
    alias: 'Pandemicabin notify when all leave cabin'
    trigger:
    - platform: state
      entity_id:
        - person.angela
        - person.michael
        - person.camille
      for: "00:15:00"
    condition:
      - condition: not
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: person.angela
                state: cabin
              - condition: state
                entity_id: person.michael
                state: cabin
              - condition: state
                entity_id: person.camille
                state: cabin
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.pancab_alarm
            state: disarmed
          - condition: state
            entity_id: 
              - input_boolean.pancab_guest_mode
            state: 'off'
    action:
      - service: notify.mobile_app_kashyyyk
        data:
          title: 'Pandemicabin Alert'
          message: 'Everyone has left the cabin'
      - service: script.pandemicabin_actionable_away

  - id: '1606704077554'
    alias: 'Pandemicabin notify when getting close'
    trigger:
      - platform: template
        value_template: >-
          {{ distance('zone.cabin', 'person.michael')|int <= 80 or
             distance('zone.cabin', 'person.angela')|int <= 80 }}
        for: "00:15:00"
    condition:
      - condition: state
        entity_id:
          - input_boolean.pancab_heat_away
        state: 'on'
      - condition: numeric_state
        entity_id: 
          - sensor.pancab_temperature_overall
        below: 67
      - condition: state
        entity_id:
          - input_boolean.pancab_guest_mode
        state: 'off'
    action:
      - service: notify.grown_ups
        data:
          title: "Panemicabin Alert"
          message: "It appears you are heading to the cabin. You might want to make it warmer."

  - id: '1610678486936'
    alias: Heat boost on tag scan
    trigger:
      - platform: tag
        tag_id: b419ea4c-5501-4517-9cef-b240f806210a
    condition:
      - condition: state
        entity_id: climate.pancab_z_wave_plus_thermostat
        state: heat
      - condition: state
        entity_id: climate.pancab_z_wave_plus_thermostat
        attribute: hvac_action
        state: idle
      - condition: template
        value_template: >-
          {{ as_timestamp(now()) - (as_timestamp(state_attr('script.heat_boost_temporary', 'last_triggered')) or 0 ) > 480}}
    action:
      - service: script.heat_boost_temporary
          
script:

  heat_boost_temporary:
    alias: "Temporary Heat Boost"
    mode: single
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.pancab_z_wave_plus_thermostat
          temperature: >-
            {{ state_attr('climate.pancab_z_wave_plus_thermostat', 'current_temperature') + 2 }}
      - wait_for_trigger:
        - platform: state
          entity_id:
            - climate.pancab_z_wave_plus_thermostat
          from: 'heat'
          to: 'idle'
        timeout: '00:07:00'
        continue_on_timeout: true
      - service: climate.set_temperature
        data:
          entity_id: climate.pancab_z_wave_plus_thermostat
          temperature: >-
            {{ states('input_number.pancab_heat_auto_setpoint') }}