input_select:
  closest_home_michael:
    name: 'Closest Home Michael'
    options:
      - 'North Harbor Tower'
      - 'Pandemicabin'

automation:
  - id: '1608339069146'
    alias: 'Set closest home'
    trigger:
      - platform: state
        entity_id: 
          - person.michael
        for: '00:05:00'
    condition: []
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.closest_home_michael
          option: >-
            {%- if closest('person.michael', states.zone).entity_id == 'zone.cabin' %}
            Pandemicabin
            {%- else -%}
            North Harbor Tower
            {%- endif -%}
            
  - id: '1608344953300'
    alias: 'Pandemicabin notify when all leave cabin'
    trigger:
    - platform: template
      value_template: >-
        {%- set atCabin = false %}
        {%- for person in states.person %}
          {%- if person.state == 'Cabin' %}
            {%- set atCabin = true %}
          {%- endif %}
        {%- endfor %}
        {{ atCabin }}
      for: "00:15:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.pancab_alarm
            state: disarmed
          - condition: state
            entity_id: input_boolean.pancab_thermostat_hold_temp
            state: 'off'
    action:
      - service: notify.mobile_app_ergisch
        data:
          title: 'Pandemicabin Alert'
          message: 'Everyone has left the cabin'
          data:
            push:
              category: pandemicabin_away
      - service: script.pandemicabin_actionable_away

  - id: '1606702211014'
    alias: 'Pandemicabin notify when far away'
    trigger:
      - platform: template
        value_template: >-
          {{ distance('zone.cabin', 'person.michael') >= 60 and
             distance('zone.cabin', 'person.angela') >= 60 }}
        for: "00:45:00"
    condition:
      - condition: state
        entity_id:
          - input_boolean.pancab_heat_away
        state: 'off'
    action:
      - service: notify.grown_ups
        data:
          title: "Panemicabin Alert"
          message: "It appears you have left. Set the heat to away"

  - id: '1606704077554'
    alias: 'Pandemicabin notify when getting close'
    trigger:
      - platform: template
        value_template: >-
          {{ distance('zone.cabin', 'device_tracker.ergisch') <= 80 or
             distance('zone.cabin', 'device_tracker.iphone') <= 80 }}
        for: "00:15:00"
    condition:
      - condition: state
        entity_id:
          - input_boolean.pancab_heat_away
        state: 'on'
      - condition: numeric_state
        entity_id: 
          - sensor.pancab_temperature_overall
        below: 67
    action:
      - service: notify.grown_ups
        data:
          title: "Panemicabin Alert"
          message: "It appears you are heading to the cabin. You might want to make it warmer."
          
script:
  test_climate_notification:
    alias: "Test of ios climate notifications"
    sequence:
      - service: notify.mobile_app_ergisch
        data:
          title: 'Pandemicabin Alert'
          message: 'Everyone has left'
          data:
            push:
              category: pandemicabin_away
      - service: script.test_action_away
  test_action_away:
    alias: Test for action away
    sequence:
      - wait_for_trigger:
        - platform: event
          event_type: ios.notification_action_fired
        timeout: '00:02:00'
        continue_on_timeout: false
      - service: notify.michael
        data:
          title: "Master HA Test"
          message: >-
            {{ wait.trigger.event.data.actionName }}
  pandemicabin_actionable_away:
    alias: "React to all away ios notification"
    sequence:
      - wait_for_trigger:
        - platform: event
          event_type: ios.notification_action_fired
          event_data:
            actionName: "AWAY_LONG_TERM"
        - platform: event
          event_type: ios.notification_action_fired
          event_data:
            actionName: "AWAY_SHORT_TERM"
        timeout: '00:02:00'
        continue_on_timeout: false
      - service: >-
          {% set actionName = wait.trigger.event.data.actionName %}
          {% if actionName == 'AWAY_LONG_TERM' %}
          script.pancab_leaving_home_long
          {% elif actionName == 'AWAY_SHORT_TERM' %}
          script.pancab_leaving_home_short
          {% endif %}