aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: Home
    night_mode_name: night
    trigger_time: 60
    alarm_volume: 8

camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - connectivity

sensor:
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - last_capture
      - recent_activity
      - captured_today
      - battery_level
      - signal_strength

light:
  - platform: aarlo

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    siren_volume: 1
    siren_duration: 10

automation:

  # Keep arlo alarm states in sync with manual alarm panel
  - id: '1607362322426'
    alias: NHT Aarlo alarm set from main alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.nht_home_alarm
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "pending" or
             states("alarm_control_panel.home_alarm") != "triggered"}}
    action:
      - entity_id: alarm_control_panel.aarlo_nht
        service: >-
          {% if trigger.to_state.state == "armed_home" %}
          alarm_control_panel.alarm_arm_home
          {% elif trigger.to_state.state == "armed_night" %}
          alarm_control_panel.alarm_arm_night
          {% elif trigger.to_state.state == "armed_away" %}
          alarm_control_panel.alarm_arm_away
          {% elif is_state("input_boolean.nht_in_home_services", "on") %}
          alarm_control_panel.alarm_arm_away
          {% else %}
          alarm_control_panel.alarm_disarm
          {% endif %}

  - id: '1607363586435'
    alias: Pandemicabin Aarlo alarm set from main alarm
    trigger:
      - platform: state
        entity_id: 
          - alarm_control_panel.pancab_alarm
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "pending" or
             states("alarm_control_panel.home_alarm") != "triggered"}}
    action:
      - entity_id: alarm_control_panel.aarlo_pandemicabin
        service: >-
          {% if trigger.to_state.state == "armed_home" %}
          alarm_control_panel.alarm_arm_away
          {% elif trigger.to_state.state == "armed_away" %}
          alarm_control_panel.alarm_arm_away
          {% else %}
          alarm_control_panel.alarm_arm_home
          {% endif %}